setwd("D:/Documents/McDaniel/ANA515/A2")
install.packages("bslib", repos = "http://cran.us.r-project.org")
install.packages("tidyverse", repos = "http://cran.us.r-project.org")
install.packages("knitr", repos = "http://cran.us.r-project.org")
install.packages("readr", repos = "http://cran.us.r-project.org")
install.packages("stringr")
library(stringr)
library(ggplot2)
library(dplyr)
library(readr)
library(tidyverse)
library(stringr)

df <- read_csv("D:/Documents/McDaniel/ANA515/A2/StormEvents_details-ftp_v1.0_d1996_c20220425.csv")
head(df)
colnames(df) 

cols_to_keep <- c("BEGIN_DAY","BEGIN_TIME","BEGIN_YEARMONTH","END_TIME","END_DAY","END_YEARMONTH","BEGIN_DATE_TIME","END_DATE_TIME","EPISODE_ID","EVENT_ID","STATE","STATE_FIPS","CZ_NAME","EVENT_TYPE","DATA_SOURCE","BEGIN_LAT","BEGIN_LON","END_LAT","END_LON","CZ_TYPE")
df_new <- df[cols_to_keep]
df_new <- df_new %>% arrange((BEGIN_YEARMONTH))
df_new$STATE = str_to_title(df_new$STATE)
df_new <- df_new[df_new$CZ_TYPE == 'C', ]
df_new <- subset(df_new, select = -c(CZ_TYPE))
df_new$STATE_FIPS <- str_pad(df_new$STATE_FIPS, width=3, side="left", pad="0")
df_new<- unite_(df_new, "FIPS", c("STATE","STATE_FIPS"),remove = FALSE)
names(df_new) <- tolower(names(df_new))
data("state")
us_state_details <- data.frame(state=state.name, region=state.region, area=state.area)
df_freq <- data.frame(table(df_new$state))
df_freq<-rename(df_freq, c("state"="Var1"))
head(df_freq)
df_merge <- merge(us_state_details,df_freq,by="state")
plot = ggplot(df_merge, aes(x=area, y = Freq)) + geom_point(aes(color = region)) + labs(x = "Area (miles^2)", y = "Storm Event Count")
head(df_merge)
head(us_state_details)
head(df_new)
plot